# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: nested_file 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "nested_file"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Mike Harris"]
  s.date = "2016-05-17"
  s.description = "nested_file"
  s.email = "mharris717@gmail.com"
  s.executables = ["nested_file"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/nested_file",
    "lib/nested_file.rb",
    "lib/nested_file/file_group.rb",
    "lib/nested_file/file_section.rb",
    "lib/nested_file/file_tag.rb",
    "lib/nested_file/put_dir.rb",
    "lib/nested_file/put_file.rb",
    "lib/nested_file/util.rb",
    "nested_file.gemspec",
    "spec/file_section_spec.rb",
    "spec/nested_file_spec.rb",
    "spec/parent_template/a.txt",
    "spec/parent_template/include_others.txt",
    "spec/parent_template/include_others_rel.txt",
    "spec/parent_template/sub2/x.txt",
    "spec/put_dir_spec.rb",
    "spec/spec_helper.rb",
    "tmp/.gitkeep",
    "unmount_all_fuse.rb",
    "util/green.gif",
    "util/package.json",
    "util/red.png",
    "util/run_specs",
    "util/watch.js",
    "vol/spawn_mount.rb",
    "vol/watch_cat.rb"
  ]
  s.homepage = "http://github.com/mharris717/nested_file"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "nested_file"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mharris_ext>, [">= 0"])
      s.add_runtime_dependency(%q<rfusefs>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<guard>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<guard-spork>, [">= 0"])
      s.add_development_dependency(%q<rb-fsevent>, ["~> 0.9"])
      s.add_development_dependency(%q<lre>, [">= 0"])
      s.add_development_dependency(%q<rr>, [">= 0"])
    else
      s.add_dependency(%q<mharris_ext>, [">= 0"])
      s.add_dependency(%q<rfusefs>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<guard-spork>, [">= 0"])
      s.add_dependency(%q<rb-fsevent>, ["~> 0.9"])
      s.add_dependency(%q<lre>, [">= 0"])
      s.add_dependency(%q<rr>, [">= 0"])
    end
  else
    s.add_dependency(%q<mharris_ext>, [">= 0"])
    s.add_dependency(%q<rfusefs>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<guard-spork>, [">= 0"])
    s.add_dependency(%q<rb-fsevent>, ["~> 0.9"])
    s.add_dependency(%q<lre>, [">= 0"])
    s.add_dependency(%q<rr>, [">= 0"])
  end
end

